// @vitest-environment happy-dom
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { RichEditor } from '../src/editor';
import { CORPUS } from './corpus';

/**
 * Generates SUPPORT.md: the measured normalization table the improvement plan
 * demands before implementation acceptance. Re-run whenever the editor
 * dependencies change; commit the diff, it IS the support table.
 *
 * The generator also asserts the gate it documents. Crepe applies its parsed
 * document in a transaction after mount, so the wait must outlast that (a 20 ms
 * window reports a false "no").
 */
const SETTLE_MS = 400;

describe('support table generation', () => {
  it(
    'writes SUPPORT.md and reports no load-time change',
    async () => {
    let loadEmittedChange = false;
    const lines: string[] = [
      '# Rich-mode normalization support table',
      '',
      'Generated by `tests/support-table.test.ts` from the checked-in corpus.',
      'Do not hand-edit. "Load emits change" must always be no: a view-only',
      'open/close must never touch the source. "Round-trip" describes what a',
      'real user edit does to the bytes.',
      '',
      '| Fixture | Load emits change | Round-trip |',
      '|---|---|---|',
    ];

    for (const fixture of CORPUS) {
      const root = document.createElement('div');
      document.body.appendChild(root);
      const editor = await RichEditor.mount(root, {
        markdown: fixture.input,
        placeholder: '',
        onChange: () => {
          loadEmittedChange = true;
        },
        onOpenLink: () => {},
      });
      await new Promise((r) => setTimeout(r, SETTLE_MS));
      const out = editor.getMarkdown();
      const roundTrip =
        out === fixture.input ? 'exact' : `normalized (expect: ${fixture.expect})`;
      lines.push(
        `| ${fixture.name} | ${loadEmittedChange ? 'YES — BUG' : 'no'} | ${roundTrip} |`,
      );
      await editor.destroy();
      root.remove();
    }
    lines.push('');

    // Assert the tracked fact, not the formatted table: re-parsing the output
    // would pass if the marker text ever changed.
    expect(loadEmittedChange, 'a load must not report a change').toBe(false);

    writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'SUPPORT.md'), lines.join('\n'));
  },
    // 16 fixtures x SETTLE_MS exceeds the 5 s default test timeout.
    30_000,
  );
});
