import { build } from 'esbuild';
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';

/**
 * Deterministic production bundle: fixed esbuild + dependency versions
 * (lockfile) and no time/hash-based output. Rebuilding from the same
 * lockfile must produce byte-identical dist/ output; the editor-web CI
 * workflow rebuilds and fails on any diff.
 *
 * Source maps are emitted as build-local debugging aids and are not committed
 * (they embed full third-party sources and would swamp review diffs).
 */
const shared = {
  bundle: true,
  minify: true,
  // Vue and Milkdown ship dev-guarded esm-bundler builds; without this they
  // spend cycles on warnings and dev-only assertions inside the web view.
  define: { 'process.env.NODE_ENV': '"production"' },
  target: ['safari16', 'es2022'],
  metafile: true,
  logLevel: 'info',
};

mkdirSync('dist', { recursive: true });

const result = await build({
  ...shared,
  entryPoints: ['src/main.ts'],
  format: 'iife',
  outfile: 'dist/editor.js',
  sourcemap: true,
  loader: { '.css': 'css' },
});

// Recorded so `npm run licenses` reproduces LICENSES.md from the same build.
writeFileSync('dist/meta.json', JSON.stringify(result.metafile));

for (const file of ['dist/editor.js', 'dist/editor.css']) {
  const { size } = statSync(file);
  console.log(`${file}: ${(size / 1024).toFixed(1)} KiB`);
}

/** Licenses the spike is allowed to ship. Anything else fails the build. */
const ALLOWED_LICENSES = new Set([
  'MIT',
  'ISC',
  'BSD-2-CLAUSE',
  'BSD-3-CLAUSE',
  'APACHE-2.0',
  '(MPL-2.0 OR APACHE-2.0)',
  '(MIT OR CC0-1.0)',
]);

/** package.json license fields vary in case and spacing; compare normalized. */
const normalizeLicense = (license) =>
  String(license ?? '')
    .replace(/\s+/g, ' ')
    .trim()
    .toUpperCase();

// License inventory is part of the build so it cannot drift from what ships.
// Keyed by resolved directory, not bare name: the same package can ship twice
// (top-level and nested) at different versions and licenses, and keying by name
// would check only whichever copy was enumerated first.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  const segments = input.split('node_modules/');
  if (segments.length < 2) continue;
  const match = segments[segments.length - 1].match(/^((@[^/]+\/)?[^/]+)/);
  if (!match) continue;

  const name = match[1];
  const packageDir = `${input.slice(0, input.length - segments[segments.length - 1].length)}${name}`;
  if (packages.has(packageDir)) continue;

  try {
    const manifest = JSON.parse(readFileSync(`${packageDir}/package.json`, 'utf8'));
    const license =
      typeof manifest.license === 'string' ? manifest.license : JSON.stringify(manifest.license);
    packages.set(packageDir, [name, manifest.version ?? '?', license || 'UNKNOWN']);
  } catch {
    packages.set(packageDir, [name, '?', 'UNKNOWN']);
  }
}

const unlicensed = [...packages.entries()].filter(
  ([, [, , license]]) => !ALLOWED_LICENSES.has(normalizeLicense(license)),
);
if (unlicensed.length > 0) {
  throw new Error(
    `unreviewed license(s) in the bundle: ${unlicensed
      .map(([dir, [name, , license]]) => `${name} (${license}) at ${dir}`)
      .join(', ')}`,
  );
}

// Codepoint order, not locale order: localeCompare depends on the host locale
// and would break the byte-identical rebuild guarantee. Version breaks ties so
// two copies of one package always print in the same order.
const byName = (a, b) =>
  a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : a[2] < b[2] ? -1 : a[2] > b[2] ? 1 : 0;
const rows = [...packages.values()].sort(byName);
writeFileSync(
  'LICENSES.md',
  [
    '# Third-party licenses bundled in dist/editor.js',
    '',
    'Generated by `npm run build` from the esbuild metafile: only code that',
    'actually ships in the bundle is listed. Do not hand-edit.',
    '',
    '| Package | Version | License |',
    '|---|---|---|',
    ...rows.map(([name, version, license]) => `| ${name} | ${version} | ${license} |`),
    '',
  ].join('\n'),
);
console.log(`LICENSES.md: ${rows.length} bundled packages`);
